README.md

- Also remove compiler-rt as it is not needed for mutang to work.

README: more instruction steps

---

unittests/MutationEngineTests.cpp

The line ASSERT_NE(nullptr, OldInstruction->getParent()); was testing garbage. It is RolledBackInstruction that has to be tested here.

MutationEngine: fix flaky test

---

include/ForkProcessSandbox.h
include/GoogleTest/GoogleTestFinder.h
include/MutationPoint.h
include/SimpleTest/SimpleTestFinder.h
include/TestFinder.h
include/TestResult.h
lib/Driver.cpp
lib/ForkProcessSandbox.cpp
lib/GoogleTest/GoogleTestFinder.cpp
lib/GoogleTest/GoogleTestRunner.cpp
lib/MutationEngine.cpp
lib/MutationOperators/AddMutationOperator.cpp
lib/MutationPoint.cpp
lib/SimpleTest/SimpleTestFinder.cpp
lib/TestResult.cpp
tools/driver/CMakeLists.txt
tools/driver/driver.cpp
unittests/GoogleTest/GoogleTestFinderTest.cpp
unittests/TestModuleFactory.cpp

Dirty and hacky, but I think it's time to sync with master.

[GoogleTest] Find mutation points

---

include/Config.h
include/GoogleTest/GoogleTestFinder.h
include/SimpleTest/SimpleTestFinder.h
include/TestFinder.h
lib/ConfigParser.cpp
lib/Driver.cpp
lib/GoogleTest/GoogleTestFinder.cpp
lib/SimpleTest/SimpleTestFinder.cpp
unittests/ConfigParserTests.cpp
unittests/DriverTests.cpp

Make distance configurable

---

include/Logger.h
lib/CMakeLists.txt
lib/ConfigParser.cpp
lib/Driver.cpp
lib/ForkProcessSandbox.cpp
lib/Logger.cpp
lib/ModuleLoader.cpp
lib/MutationOperators/NegateConditionMutationOperator.cpp
lib/SQLiteReporter.cpp
lib/SimpleTest/SimpleTestFinder.cpp
lib/Toolchain/ObjectCache.cpp
tools/driver/driver.cpp

- Added logger class
- Replaced some printf's with new logger
- Replaced uses of outs() and errs() with new logger

Add Logger

---

lib/SimpleTest/SimpleTestFinder.cpp

- Use `make_unique`
- LLVM formatting
- Removed convolution control flow in worklist algorithm 
- Use intuitive for loops for Function/BasicBlock/Instruction

Small improvements

---

include/MutationOperators/NegateConditionMutationOperator.h
include/MutationOperators/RemoveVoidFunctionMutationOperator.h
include/SQLiteReporter.h
lib/ForkProcessSandbox.cpp

Found and fixed some issues when compiling on my Linux workstation.

Fix compilation on Linux

---

lib/SQLiteReporter.cpp
unittests/SQLiteReporterTest.cpp

SQLiteReporter tests

---

unittests/CMakeLists.txt

This is for https://github.com/mull-project/mull/issues/43 which I think we are not going to fix. @AlexDenisov, I don't see a better way of doing this other than you did.
I am adding the comment to better clarify the state of the art. Let's close the issue unless you have something better in mind.

Not going to fix duality MullTestSuite vs MullUnitTests.

---

include/Config.h
include/ConfigParser.h
unittests/DriverTests.cpp

Add dylib support to Config

---

include/Result.h
include/SQLiteReporter.h
lib/Driver.cpp
lib/SQLiteReporter.cpp
tools/driver/driver.cpp
unittests/SQLiteReporterTest.cpp

One thing which can be discussed: if calculation of start and time times should be done in `driver.cpp/main` or in `Driver::run()`.

Write start and end times to SQLite.

---

.travis.yml
Makefile

#115
Unfortunately, It seems impossible for Travis script to support Rust at the moment

Add .travis.yml

---

include/Config.h
include/ConfigParser.h
lib/SQLiteReporter.cpp
unittests/ConfigParserTests.cpp
unittests/SQLiteReporterTest.cpp

Add dynamicLibrary file check

---

.gitignore
CMakeLists.txt
projects/CMakeLists.txt

This projects/ folder will contain:
- mull-auto-test project
- mull and klee tutorial 2
- other small projects that we might use a demo projects

CMake: add_subdirectory projects/

---

include/Config.h
include/MutationOperators/MathMulMutationOperator.h
lab/simple_test/mutation_operators/math_mul/Makefile
lab/simple_test/mutation_operators/math_mul/main.c
lab/simple_test/mutation_operators/math_mul/math_mul.c
lab/simple_test/mutation_operators/math_mul/math_mul.h
lib/CMakeLists.txt
lib/Driver.cpp
lib/MutationOperators/MathMulMutationOperator.cpp
unittests/ConfigParserTests.cpp
unittests/DriverTests.cpp
unittests/MutationPointTests.cpp
unittests/TestModuleFactory.cpp
unittests/TestModuleFactory.h
unittests/fixtures/fixture_simple_test_math_mul_operator.ll

New operator: MathMulMutationOperator.

---

README.md

README: update supported mutation operators.

---

include/Config.h
include/MutationOperators/ScalarValueMutationOperator.h
lab/simple_test/mutation_operators/scalar_value/Makefile
lab/simple_test/mutation_operators/scalar_value/main.c
lab/simple_test/mutation_operators/scalar_value/scalar_value.c
lib/CMakeLists.txt
lib/Driver.cpp
lib/MutationOperators/ScalarValueMutationOperator.cpp
unittests/ConfigParserTests.cpp
unittests/MutationPointTests.cpp
unittests/SimpleTest/SimpleTestFinderTest.cpp
unittests/TestModuleFactory.cpp
unittests/TestModuleFactory.h
unittests/fixtures/fixture_simple_test_scalar_value_operator.ll

I need to get back to Julia/openlibm to see more functions and more real-world scenarios to polish further however the results for `acos` are quite impressive:
```
Mull Report: openlibm-mull
01.10.2017 23:56:55
Tests:1
Mutants:54
Survived Mutants:17
Killed Mutants:37
Total time:2s 614ms
Execution Time:359ms
Weakly Killed Mutants:0
Strongly Killed Mutants:37
Max distance:0
Min distance:0
Mean distance:0
Mutation Score:69%
```
One problem: caret is often broken 😄

New operator: ScalarValueMutationOperator.

---

lib/MutationOperators/ScalarValueMutationOperator.cpp

With this PR ScalarValueMutationOperator now outputs the diagnostics in the following format:
```
Scalar Value Replacement: 0 -> 1
```
As discussed I am doing this without a special class for meta information so there is a work that is done twice.

ScalarValueMutationOperator: diagnostics "from -> to".

---

Examples/HelloWorld/Makefile
Makefile.centos
Makefile.macos
Makefile.ubuntu

Some minor warnings appear but that's fine for now.

HelloWorld: simplify compile flags, compile on CentOS and Ubuntu.

---

Docs/HowToRunMull.md
Makefile.macos

HowToRunMull: Expand step 2.

---

include/CustomTestFramework/CustomTestRunner.h
include/ForkProcessSandbox.h
include/GoogleTest/GoogleTestRunner.h
include/SimpleTest/SimpleTestRunner.h
include/TestResult.h
include/TestRunner.h
lib/CustomTestFramework/CustomTestRunner.cpp
lib/Driver.cpp
lib/ForkProcessSandbox.cpp
lib/GoogleTest/GoogleTestRunner.cpp
lib/SQLiteReporter.cpp
lib/SimpleTest/SimpleTestRunner.cpp
unittests/CustomTestFramework/CustomTestRunnerTests.cpp
unittests/DriverTests.cpp
unittests/ForkProcessSandboxTest.cpp
unittests/SQLiteReporterTest.cpp
unittests/TestRunnersTests.cpp

Runners return status

---

Docs/GettingStartedUbuntu.md

Docs/Ubuntu: More precise instruction.

---

include/MullModule.h
include/MutationPoint.h
lib/Driver.cpp
lib/ModuleLoader.cpp
lib/MullModule.cpp
lib/MutationPoint.cpp
unittests/MutationOperators/ScalarValueMutationOperatorTest.cpp
unittests/MutationPointTests.cpp
unittests/TestModuleFactory.cpp
unittests/TestRunnersTests.cpp

Everything seems to be working now, but let's not merge it yet.
- I want to make sure it does not break things
- I want to measure if memory consumption has dropped
- I want to clean up the driver a bit, it becomes messy
P.S. Dependent on #277

Clone module

---

Docker/mull-ubuntu/Makefile
Docker/mull-ubuntu/README.md

Docker/mull-ubuntu: Create container with a shared folder.

---

README.md

Also add SE topic with Henry Coles's answer:
`Mutation testing: is it useful for assessing test quality?`
[skip ci]

Open questions: Automatic test generation.

---

Docs/EquivalentMutations.md

Docs/EquivalentMutations: first 4 mutations.

---

LICENSE
README.md

Apache License 2.0.

---

include/Driver.h
include/Toolchain/ObjectCache.h
lib/Driver.cpp
lib/Toolchain/ObjectCache.cpp

Object cache

---

lib/Driver.cpp

Disable Fail Fast by default.

---

include/Driver.h
lib/Driver.cpp

Rename variables in driver

---

Docs/HowToRunMull.md

Fix broken "How to get LLVM Bitcode" link

---

Docs/HowToRunMull.md

Apologies, didn't realise there were 2 broken links on the same page 😩

Moar broken links

---

Docs/GettingStartedMacOS.md
Docs/GettingStartedUbuntu.md

Add build system initialization to the documentation

---

include/CustomTestFramework/CustomTestRunner.h
include/GoogleTest/GoogleTestRunner.h
include/SimpleTest/SimpleTestRunner.h
include/TestRunner.h
lib/CustomTestFramework/CustomTestRunner.cpp
lib/Driver.cpp
lib/GoogleTest/GoogleTestRunner.cpp
lib/SimpleTest/SimpleTestRunner.cpp
unittests/CustomTestFramework/CustomTestRunnerTests.cpp
unittests/GoogleTest/GoogleTestFinderTest.cpp
unittests/TestRunnersTests.cpp

Thread safe test runners

---

README.md

Add 'citation' section

---

include/CustomTestFramework/CustomTestRunner.h
include/GoogleTest/GoogleTestRunner.h
include/MullModule.h
include/MutationPoint.h
include/Parallelization/Tasks/MutantExecutionTask.h
include/Parallelization/Tasks/OriginalCompilationTask.h
include/SimpleTest/SimpleTestRunner.h
include/TestRunner.h
include/Toolchain/Mangler.h
include/Toolchain/Toolchain.h
lib/Driver.cpp
lib/GoogleTest/GoogleTestRunner.cpp
lib/MullModule.cpp
lib/MutationPoint.cpp
lib/Reporters/SQLiteReporter.cpp
lib/SimpleTest/SimpleTestRunner.cpp
lib/TestRunner.cpp
lib/Toolchain/Mangler.cpp
lib/Toolchain/ObjectCache.cpp
lib/Toolchain/Resolvers/InstrumentationResolver.cpp
lib/Toolchain/Toolchain.cpp
unittests/CustomTestFramework/CustomTestRunnerTests.cpp
unittests/DriverTests.cpp
unittests/GoogleTest/GoogleTestFinderTest.cpp
unittests/JunkDetection/CXXJunkDetectorTests.cpp
unittests/MutationPointTests.cpp
unittests/TestRunnersTests.cpp

Extracting pieces from #397 to make it smaller.

Minor NFC changes

---

Examples/HelloWorld/Makefile
include/TestFrameworks/TestFrameworkFactory.h
lib/TestFrameworks/TestFrameworkFactory.cpp
tools/driver-cxx/driver-cxx.cpp
tools/driver/driver.cpp
unittests/DriverTests.cpp

Namely:
- cache-dir
- disable-cache
- test-framework

[mull-cxx] Add more CLI options

---

cmake/fixtures.cmake
include/ObjectLoader.h
lab/dylibs_and_objects/CMakeLists.txt
lib/CMakeLists.txt
lib/ObjectLoader.cpp
unittests/DriverTests.cpp

Context: https://bugs.llvm.org/show_bug.cgi?id=35371

Fix JITting of object files

---

include/TestFrameworks/GoogleTest/GoogleTestRunner.h
lib/TestFrameworks/GoogleTest/GoogleTestRunner.cpp

[GoogleTest] Do not mock Google Test driver

---

.travis.yml
LLVMCompatibility/4.x.x/LLVMCompatibility.h
LLVMCompatibility/5.x.x/LLVMCompatibility.h
LLVMCompatibility/6.x.x/LLVMCompatibility.h
LLVMCompatibility/7.x.x/LLVMCompatibility.h
LLVMCompatibility/8.x.x/CMakeLists.txt
LLVMCompatibility/8.x.x/LLVMCompatibility.cpp
LLVMCompatibility/8.x.x/LLVMCompatibility.h
include/TestFrameworks/CustomTestFramework/CustomTestRunner.h
include/TestFrameworks/GoogleTest/GoogleTestRunner.h
include/TestFrameworks/SimpleTest/SimpleTestRunner.h
include/Toolchain/Resolvers/InstrumentationResolver.h
include/Toolchain/Resolvers/MutationResolver.h
infrastructure/helpers/variables.yaml
lib/Mutators/AndOrReplacementMutator.cpp
lib/Toolchain/Resolvers/InstrumentationResolver.cpp
lib/Toolchain/Resolvers/MutationResolver.cpp

Add LLVM 8.0 support

---

README.md

[Docs] Include examples into README.md

---

include/mull/Parallelization/Tasks/MutantExecutionTask.h
include/mull/Parallelization/Tasks/OriginalTestExecutionTask.h
include/mull/TestFrameworks/CustomTestFramework/CustomTestRunner.h
include/mull/TestFrameworks/CustomTestFramework/CustomTest_Test.h
include/mull/TestFrameworks/GoogleTest/GoogleTestRunner.h
include/mull/TestFrameworks/GoogleTest/GoogleTest_Test.h
include/mull/TestFrameworks/SimpleTest/SimpleTestRunner.h
include/mull/TestFrameworks/TestRunner.h
lib/Driver.cpp
lib/Parallelization/Tasks/MutantExecutionTask.cpp
lib/Parallelization/Tasks/OriginalTestExecutionTask.cpp
lib/TestFrameworks/CustomTestFramework/CustomTestFinder.cpp
lib/TestFrameworks/CustomTestFramework/CustomTestRunner.cpp
lib/TestFrameworks/CustomTestFramework/CustomTest_Test.cpp
lib/TestFrameworks/GoogleTest/GoogleTestFinder.cpp
lib/TestFrameworks/GoogleTest/GoogleTestRunner.cpp
lib/TestFrameworks/GoogleTest/GoogleTest_Test.cpp
lib/TestFrameworks/SimpleTest/SimpleTestRunner.cpp
tests/CustomTestFramework/CustomTestFinderTests.cpp
tests/CustomTestFramework/CustomTestRunnerTests.cpp
tests/GoogleTest/GoogleTestFinderTest.cpp
tests/TestRunnersTests.cpp

Use static constructors from Program intead of *Test

---

CMakeLists.txt
Examples/HelloWorld/Makefile
cmake/cpack.cmake
infrastructure/Vagrantfile
infrastructure/freebsd-playbook.yaml
infrastructure/helpers/integration-tests.yaml
infrastructure/helpers/variables.yaml

Add FreeBSD playbook

---

.travis.yml
cmake/packaging/cpack.PKG-macOS.cmake
infrastructure/debian-playbook.yaml
infrastructure/helpers/build-mull.yaml
infrastructure/helpers/variables.yaml

Switch back to PackageMakaer on macOS

---

CHANGELOG.md
CMakeLists.txt

Prepare next release 0.2.0

---

CHANGELOG.md
include/mull/JunkDetection/CXX/Visitors/AndOrReplacementVisitor.h
include/mull/Mutators/AndOrReplacementMutator.h
include/mull/Mutators/Mutator.h
lib/CMakeLists.txt
lib/JunkDetection/CXX/CXXJunkDetector.cpp
lib/JunkDetection/CXX/Visitors/AndOrReplacementVisitor.cpp
tests/JunkDetection/CXXJunkDetectorTests.cpp
tests/fixtures/mutators/and_or_replacement_cpp/CMakeLists.txt
tests/fixtures/mutators/and_or_replacement_cpp/junk.cpp

Add junk detection for AndOrReplacement mutator

---

include/mull/JunkDetection/CXX/Visitors/ReplaceCallVisitor.h
include/mull/Mutators/Mutator.h
include/mull/Mutators/ReplaceCallMutator.h
lib/CMakeLists.txt
lib/JunkDetection/CXX/CXXJunkDetector.cpp
lib/JunkDetection/CXX/Visitors/ReplaceCallVisitor.cpp
tests/JunkDetection/CXXJunkDetectorTests.cpp
tests/fixtures/mutators/replace_call/CMakeLists.txt
tests/fixtures/mutators/replace_call/junk.cpp

Junk detection for ReplaceCall mutator

---

README.md
documentation/hacking.md

These appear to be mostly typos.

Fix some spelling mistakes

---

CHANGELOG.md
include/mull/MutationPoint.h
lib/MutationPoint.cpp
lib/Mutators/AndOrReplacementMutator.cpp
lib/Mutators/ConditionalsBoundaryMutator.cpp
lib/Mutators/MathAddMutator.cpp
lib/Mutators/MathDivMutator.cpp
lib/Mutators/MathMulMutator.cpp
lib/Mutators/MathSubMutator.cpp
lib/Mutators/NegateConditionMutator.cpp
lib/Mutators/RemoveVoidFunctionMutator.cpp
lib/Mutators/ReplaceAssignmentMutator.cpp
lib/Mutators/ReplaceCallMutator.cpp
lib/Mutators/ScalarValueMutator.cpp
tests/MutationPointTests.cpp
tests/Mutators/ScalarValueMutatorTest.cpp
tests/UniqueIdentifierTests.cpp

Fixed Original Value use-after-free issue

---

documentation/hacking.md

Update 'Hacking on Mull' docs

---

CHANGELOG.md
CMakeLists.txt

Release 0.4.0

---

CHANGELOG.md

CHANGELOG: Add Mutation Testing Elements

---

include/mull/Config/Configuration.h
lib/Config/Configuration.cpp
tests/DriverTests.cpp

Remove fork config option

---

CHANGELOG.md
include/mull/JunkDetection/CXX/Visitors/ScalarValueVisitor.h
include/mull/Mutators/Mutator.h
include/mull/Mutators/ScalarValueMutator.h
lib/CMakeLists.txt
lib/JunkDetection/CXX/CXXJunkDetector.cpp
lib/JunkDetection/CXX/Visitors/ScalarValueVisitor.cpp
tests/JunkDetection/CXXJunkDetectorTests.cpp
tests/fixtures/mutators/scalar_value/CMakeLists.txt
tests/fixtures/mutators/scalar_value/junk.cpp

This is an initial implementation, it does not cover all the cases, but
should be a good start.
Closes #484.

Junk Detection for the scalar value mutator

---

include/mull/JunkDetection/CXX/Visitors/BinaryVisitor.h
include/mull/Mutators/CXX/BitwiseMutators.h
include/mull/Mutators/Mutator.h
lib/JunkDetection/CXX/CXXJunkDetector.cpp
lib/Mutators/CXX/BitwiseMutators.cpp
lib/Mutators/CXX/CMakeLists.txt
lib/Mutators/MutatorsFactory.cpp
tests/JunkDetection/CXXJunkDetectorTests.cpp
tests/MutatorsFactoryTests.cpp
tests/fixtures/mutators/CMakeLists.txt
tests/fixtures/mutators/bitwise/CMakeLists.txt
tests/fixtures/mutators/bitwise/bitops.cpp
tests/fixtures/mutators/bitwise/shifts.cpp

Add bitwise mutators

---

include/mull/Filters/FilePathFilter.h
lib/Filters/FilePathFilter.cpp
tools/driver-cxx/driver-cxx.cpp

driver-cxx and FilePathFilter: whitelisting paths via -include-path

---

lib/JunkDetection/CXX/CompilationDatabase.cpp
lib/JunkDetection/CXX/CompilationDatabaseParser.h
tests/JunkDetection/CompilationDatabaseTests.cpp
tests/fixtures/junk_detection/compdb/db_with_arguments.json
tests/fixtures/junk_detection/compdb/db_with_fullpath_compiler.json
tests/fixtures/junk_detection/compdb/db_with_output.json

Fix compilation database parsing error

---

CHANGELOG.md
CMakeLists.txt

Bump version

---

include/mull/AST/ASTMutation.h
include/mull/AST/ASTMutationStorage.h
include/mull/JunkDetection/CXX/ASTStorage.h
include/mull/Mutators/Mutator.h
lib/AST/ASTMutationStorage.cpp
lib/CMakeLists.txt
lib/JunkDetection/CXX/ASTStorage.cpp
lib/JunkDetection/CXX/CXXJunkDetector.cpp
lib/Reporters/ASTSourceInfoProvider.cpp

This is a very important step towards having white AST search merged easily.

ASTMutationStorage: store more AST information about the mutations

---

lib/JunkDetection/CXX/CompilationDatabase.cpp
tests-lit/CMakeLists.txt
tests-lit/lit.cfg
tests-lit/tests/junk_detection/05_compilation_database_escaped_path/compile_commands.json.template
tests-lit/tests/junk_detection/05_compilation_database_escaped_path/sample.cpp
tests/JunkDetection/CompilationDatabaseTests.cpp
tests/fixtures/junk_detection/compdb/CMakeLists.txt
tests/fixtures/junk_detection/compdb/db_with_escaped_quotes.json

Junk detection: command contains escaped quotes 

---

tests/CMakeLists.txt
tests/Helpers/MutationArtefact.cpp
tests/Helpers/MutationArtefact.h
tests/Helpers/MutationTestBed.cpp
tests/Helpers/MutationTestBed.h
tests/Mutations-E2E/Mutation_Arithmetic_Add_Test.cpp

I am not sure about the names of the classes but it works perfectly :)

MutationTestBed class: encapsulate creation of mutation content for unit tests

---

include/mull/AST/ASTScalarMutationMatcher.h
include/mull/AST/ASTVisitor.h
include/mull/JunkDetection/CXX/Visitors/ScalarValueVisitor.h
include/mull/JunkDetection/CXX/Visitors/VisitorParameters.h
lib/AST/ASTScalarMutationMatcher.cpp
lib/AST/ASTVisitor.cpp
lib/CMakeLists.txt
lib/JunkDetection/CXX/Visitors/ScalarValueVisitor.cpp
tests-lit/tests/white-ast-search/scalar/01_return_value/compile_commands.json.template
tests-lit/tests/white-ast-search/scalar/01_return_value/sample.cpp
tests/CMakeLists.txt
tests/JunkDetection/CXXJunkDetectorTests.cpp
tests/Mutations-E2E/Scalar/01_Mutation_Scalar_ReturnValue_Test.cpp

ASTVisitor: recognize scalars in return statements

---

.github/workflows/ci-macos.yml
.travis.yml
CMakeLists.txt
infrastructure/helpers/build-mull.yaml
lib/CMakeLists.txt

IIRC, macOS builds were more stable on Travis.
This is a work in progress.

Back to travis again

---

CMakeLists.txt
lib/Bitcode.cpp
lib/BitcodeLoader.cpp
lib/Driver.cpp
lib/Instrumentation/DynamicCallTree.cpp
lib/Mutators/MutatorsFactory.cpp
lib/Mutators/NegateConditionMutator.cpp
lib/Mutators/RemoveVoidFunctionMutator.cpp
lib/Mutators/ReplaceCallMutator.cpp
lib/Mutators/ScalarValueMutator.cpp
lib/Parallelization/Tasks/DryRunMutantExecutionTask.cpp
lib/Parallelization/Tasks/LoadBitcodeFromBinaryTask.cpp
lib/Parallelization/Tasks/MutantExecutionTask.cpp
lib/TestFrameworks/NativeTestRunner.cpp
lib/TestFrameworks/TestFrameworkFactory.cpp
tests/DriverTests.cpp
tests/MutationTestingElementsReporterTest.cpp
tests/SQLiteReporterTest.cpp
tests/TestModuleFactory.cpp
tests/TestRunnersTests.cpp
tests/TesteesTests.cpp
tools/mull-cxx/CLIOptions.cpp
tools/mull-cxx/mull-cxx.cpp

Bump C++ version

---

CMakeLists.txt
LLVMCompatibility/3.9.x/LLVMCompatibility.cpp
LLVMCompatibility/4.x.x/LLVMCompatibility.cpp
LLVMCompatibility/5.x.x/LLVMCompatibility.cpp
LLVMCompatibility/6.x.x/LLVMCompatibility.cpp
include/mull/AST/ASTFinder.h
include/mull/Filters/FilePathFilter.h
include/mull/MutationPoint.h
include/mull/ObjectLoader.h
include/mull/Reporters/SourceCodeReader.h
lib/AST/ASTVisitor.cpp
lib/Driver.cpp
lib/JunkDetection/CXX/Visitors/RemoveVoidFunctionVisitor.cpp
lib/MutationPoint.cpp
lib/Mutators/CXX/ArithmeticMutators.cpp
lib/Mutators/CXX/BitwiseMutators.cpp
lib/Mutators/CXX/LogicalAndToOr.cpp
lib/Mutators/CXX/LogicalOrToAnd.cpp
lib/Mutators/CXX/NumberMutators.cpp
lib/Mutators/CXX/RelationalMutators.cpp
lib/Mutators/CXX/RemoveNegation.cpp
lib/ObjectLoader.cpp
lib/Parallelization/Tasks/MutantExecutionTask.cpp
tools/internal/mutator-validator/mutator-validator.cpp

Fix a bunch of warnings and add `-Wall` to CXXFLAGS.

Build with -Wall

---

docs/HackingOnMull.rst

I just run into the same issue that was described in #657 and the solution mentioned there worked for me. So I added a short hint to HackingOnMull.rst.

Add a short hint regarding #657 to HackingOnMull.rst

---

CMakeLists.txt
tests/CMakeLists.txt

Use CTest and follow recommended practices.
Took some suggestions from this piece: https://cliutils.gitlab.io/modern-cmake/chapters/testing.html

cmake: Refactor test handling

---

docs/OpenSSLTutorial.rst

Found some mistakes in the docs.
disclaimer: I'm not a native speaker either...

[Docs] typos and such

---

tests-lit/tests/invalid-input/05-elements-reporter-but-no-compdb/compile_commands.json.template
tests-lit/tests/invalid-input/05-elements-reporter-but-no-compdb/sample.cpp
tools/mull-cxx/CLIOptions.cpp
tools/mull-cxx/CLIOptions.h
tools/mull-cxx/mull-cxx.cpp

mull-cxx: raise error if Elements reporter is used without compilation DB

---

CHANGELOG.md
CMakeLists.txt
docs/Installation.rst

@stanislaw anything else I should mention?

Release 0.9.0

---

docs/generated/CLIOptions.rst
include/mull/Config/Configuration.h
lib/Config/Configuration.cpp
lib/Driver.cpp
lib/Toolchain/Linker.cpp
tests-lit/CMakeLists.txt
tests-lit/Makefile
tests-lit/tests/keep-temps/01/main.c
tools/mull-cxx/CLIOptions.cpp
tools/mull-cxx/CLIOptions.h
tools/mull-cxx/mull-cxx.cpp

Delete temp files

---

docs/generated/CLIOptions.rst
docs/generated/Mutators.rst
lib/Filters/FilePathFilter.cpp
tools/mull-cxx/CLIOptions.cpp

Mention which regex engine is used

---

include/mull/Bitcode.h
include/mull/BitcodeLoader.h
include/mull/Parallelization/Tasks/BitcodeLoadingTask.h
include/mull/Parallelization/Tasks/LoadBitcodeFromBinaryTask.h
lib/Bitcode.cpp
lib/BitcodeLoader.cpp
lib/Parallelization/Tasks/BitcodeLoadingTask.cpp
lib/Parallelization/Tasks/LoadBitcodeFromBinaryTask.cpp
tests/Helpers/MutationTestBed.cpp
tests/JunkDetection/CXXJunkDetectorTests.cpp
tests/MutationFilters/MutationFilterTests.cpp
tests/MutationPointTests.cpp
tests/MutationTestingElementsReporterTest.cpp
tests/Mutators/ConditionalsBoundaryMutatorTests.cpp
tests/Mutators/NegateConditionMutatorTest.cpp
tests/Mutators/ScalarValueMutatorTest.cpp
tests/SQLiteReporterTest.cpp
tests/TestModuleFactory.cpp
tests/TestModuleFactory.h
tools/mull-cxx/mull-cxx.cpp

Do not share contexts between modules

---

tests-lit/tests/command_line_input_validation/valid_input/01_executable_is_dot_slash_relative_path_binary/main.c
tests-lit/tests/invalid-input/06-input-file-does-not-exist/sample.cpp
tools/mull-cxx/mull-cxx.cpp
tools/mull-runner/mull-runner.cpp

mull-cxx and mull-runner: use real_path to expand relative paths

---

include/mull/Reporters/MutationTestingElementsReporter.h
include/mull/Reporters/PatchesReporter.h
include/mull/Reporters/SQLiteReporter.h
lib/Reporters/MutationTestingElementsReporter.cpp
lib/Reporters/PatchesReporter.cpp
lib/Reporters/SQLiteReporter.cpp
tests-lit/tests/mutation_testing_elements/01_mutation_testing_elements_report/sample.cpp
tests-lit/tests/patch-reporter/equality/main.cpp
tests/MutationTestingElementsReporterTest.cpp
tools/CLIOptions/CLIOptions.cpp
tools/CLIOptions/CLIOptions.h
tools/mull-cxx/mull-cxx.cpp

Solves: https://github.com/mull-project/mull/issues/920

Include command line parameters and tool info in output

---

include/mull/Reporters/GithubAnnotationsReporter.h
include/mull/Reporters/Reporter.h
lib/CMakeLists.txt
lib/Reporters/GithubAnnotationsReporter.cpp
tests-lit/tests/github-reporter/equality/main.cpp
tests-lit/tests/github-reporter/shift/main.cpp
tools/CLIOptions/CLIOptions.cpp

Report GitHub annotation style
https://github.com/mull-project/mull/issues/738

Add reporter for GithubAnnotations

---

docs/Features.rst

Fix stryker-mutator links

---

lib/Reporters/PatchesReporter.cpp
tests-lit/tests/patch-reporter/shift/main.cpp

Path was not quite correct, missing a starting slash

minor fix for path in patches

---

include/mull/BitcodeMetadataReader.h
include/mull/JunkDetection/CXX/ASTStorage.h
include/mull/JunkDetection/CXX/CompilationDatabase.h
include/mull/Reporters/MutationTestingElementsReporter.h
lib/BitcodeMetadataReader.cpp
lib/JunkDetection/CXX/ASTStorage.cpp
lib/JunkDetection/CXX/CompilationDatabase.cpp
lib/Reporters/MutationTestingElementsReporter.cpp
lib/Reporters/PatchesReporter.cpp
tests/JunkDetection/CompilationDatabaseTests.cpp
tools/mull-cxx/mull-cxx.cpp
tools/mull-runner/MutantExtractor.cpp
tools/mull-runner/mull-runner.cpp

Use std::unordered_map

---

tools/mull-runner/MutantExtractor.cpp
tools/mull-runner/MutantExtractor.h

Deduplicate mutants as part of the mull-runner

---

include/mull/Filters/BlockAddressFunctionFilter.h
lib/CMakeLists.txt
lib/Driver.cpp
lib/Filters/BlockAddressFunctionFilter.cpp
tests-lit/tests/blockaddress/main.c
tests-lit/tests/blockaddress/mull.yml

Do not mutate functions with blockaddress taken

---

include/mull/Filters/GitDiffReader.h
lib/Config/ConfigurationOptions.cpp
lib/Driver.cpp
lib/Filters/GitDiffFilter.cpp
lib/MutantRunner.cpp
lib/MutationsFinder.cpp
tools/mull-cxx-frontend/src/MullASTMutator.cpp
tools/mull-cxx-frontend/src/MullASTMutator.h
tools/mull-runner/MergeInstProfile.cpp
tools/mull-runner/mull-runner.cpp

While experimenting with mull, I ran in to a few issues when building. The only "serious" hurdle was a missing header causing compilation to fail. While at it, I took the liberty of fixing a few warnings as well.
I figured I'd share my changes in the event that you would like to incorporate them upstream.

Address misc. build issues and warnings

---

docs/Tutorials.rst
docs/tutorials/DisableMutantsWithAnnotations.rst
include/mull/Filters/Filters.h
include/mull/Filters/ManualFilter.h
include/mull/Mutators/MutatorsFactory.h
include/mull/Reporters/SourceManager.h
infrastructure/devcontainer_post_create.sh
infrastructure/generator.py
infrastructure/templates/vscode/c_cpp_properties.json.mustache
lib/CMakeLists.txt
lib/Driver.cpp
lib/Filters/Filters.cpp
lib/Filters/ManualFilter.cpp
lib/Mutators/MutatorsFactory.cpp
lib/Reporters/SourceManager.cpp
tests/integration/filters/manual/header.h
tests/integration/filters/manual/header2.h
tests/integration/filters/manual/main.c
tests/integration/filters/manual/mull.yml

Fixes https://github.com/mull-project/mull/issues/791

Ignore mutations by using source code annotations
