mull-project/mull

README.md
I have updated LLVM to [20ebcfc5d130082e30ee4b095ecaf1dcf9f57239](https://github.com/llvm-mirror/llvm/commit/20ebcfc5d130082e30ee4b095ecaf1dcf9f57239) and verified that current code which is run by MutangUnitTests target works. Let me know if there is a better way of managing the current LLVM's commit than to keep it in README 😸
=> README: add note about current LLVM commit

include/MutationEngine.h, include/MutationOperators/AddMutationOperator.h, include/MutationOperators/MutationOperator.h, include/MutationPoint.h, lib/Driver.cpp, lib/MutationEngine.cpp, lib/MutationOperators/AddMutationOperator.cpp, lib/MutationPoint.cpp, lib/TestFinders/SimpleTestFinder.cpp, unittests/MutationEngineTests.cpp, unittests/SimpleTestFinderTest.cpp, unittests/TestRunnersTests.cpp
MutationPointAddress is introduced to store address of MutationPoint to allow MutationOperator to find that mutation point in a clone of original module.
Mutation operator now applies mutation to a module, which is given to it as argument, using the MutationPointAddress to look up for mutation point.
Value `&V` argument in `AddMutationOperator::applyMutation` is not used, and is left as deprecated for removal when it is clear it will not be needed when "remote JIT" is in place.
=> Introduce MutationPointAddress

README.md, lib/TestRunners/SimpleTestRunner.cpp
1223b84c3018ba3b1148da49a85cf8f181812f2b
Updated MutangResolver to be based on new JITSymbolResolver class. Corresponding RuntimeDyld::SymbolInfo symbols are replaced with new JITSymbol classes.
=> Update to the latest LLVM: 1223b84

include/Config.h, include/ConfigParser.h, lib/CMakeLists.txt, lib/ConfigParser.cpp, tools/driver/driver.cpp, unittests/ConfigParserTests.cpp
- Use [LLVM's YAML I/O](http://llvm.org/docs/YamlIO.html) Library for parsing the configuration file.
- Consistent options: everything now uses an underscore (e.g. dry_run instead of DryRun).
- Config is no longer a unique pointer. If something fails you end up with the default config. If this is not the desired behavior, we could pass the config by reference and have the function return a bool or use as a 3rd option we could use the llvm::Expect<T> type.
=> Use LLVM Yaml Traits for config

unittests/ForkProcessSandboxTest.cpp
=> Fix timeout for tests running on a cold start (fixes #54).

README.md, lib/GoogleTest/GoogleTestFinder.cpp, lib/ModuleLoader.cpp
- Updates Mull to work against this LLVM commit:
```
commit dc30ded6fb9526aba31a86b97e8f69fc9baece00
Author: Justin Lebar <jlebar@google.com>
Date:   Wed Jan 18 00:29:53 2017 +0000
```
- Small tweak of GoogleTestFinder was needed:
class.testing::TestInfo functions are no longer under sequential type but pointer type.
=> Update code to work against newer LLVM.

include/Config.h, include/ConfigParser.h, include/Driver.h, include/GoogleTest/GoogleTestFinder.h, include/MutationOperators/AddMutationOperator.h, include/MutationOperators/NegateConditionMutationOperator.h, include/MutationOperators/RemoveVoidFunctionMutationOperator.h, lib/Driver.cpp, lib/GoogleTest/GoogleTestFinder.cpp, lib/MutationOperators/AddMutationOperator.cpp, lib/MutationOperators/NegateConditionMutationOperator.cpp, lib/MutationOperators/RemoveVoidFunctionMutationOperator.cpp, tools/driver/driver.cpp, unittests/ConfigParserTests.cpp, unittests/DriverTests.cpp, unittests/GoogleTest/GoogleTestFinderTest.cpp
=> Make Mutation Operators configurable

unittests/CMakeLists.txt, unittests/ConfigParserTestFixture.h, unittests/ConfigParserTests.cpp
The plan was to use `TEST_F` instead of `TEST`  everywhere possible. However it wen't ok only for `ConfigParserTest`. For other tests I'm facing problems, can't figure out how to resolve them for now.  I'll keep working on other tests later.
=> Use fixtures (google test framework) in ConfigParser unit tests

include/Rust/RustTestRunner.h, lab/rust/Makefile, lib/Driver.cpp, lib/ForkProcessSandbox.cpp, lib/Rust/RustTestFinder.cpp, lib/Rust/RustTestRunner.cpp, unittests/Rust/Driver_Rust_Test.cpp, unittests/fixtures/fixture_rust.ll
Also update fixtures against stable rustc compiler:
```
rustc 1.14.0 (e8a012324 2016-12-16)
binary: rustc
commit-hash: e8a0123241f0d397d39cd18fcc4e5e7edde22730
commit-date: 2016-12-16
host: x86_64-apple-darwin
release: 1.14.0
LLVM version: 3.9
```
=> RustTestRunner is configured to produce correct output.

include/MutationPoint.h, lib/Context.cpp, lib/Driver.cpp, lib/MutationOperators/AddMutationOperator.cpp, lib/MutationPoint.cpp, lib/SimpleTest/SimpleTestFinder.cpp, unittests/MutationPointTests.cpp, unittests/Rust/RustTestRunnerTest.cpp, unittests/TestModuleFactory.cpp, unittests/TestRunnersTests.cpp
- Makes more explicit name: `cloneModuleAndApplyMutation` and moves compilation to be outside of MutationPoint class.
- Fixes libc test fixture identifier.
- A couple of naming improvements in unit tests.
=> Cleanup: remove deprecated method applyMutation.

CMakeLists.txt, include/Config.h, include/ConfigParser.h, tools/driver/driver.cpp, unittests/DriverTests.cpp, unittests/Rust/Driver_Rust_Test.cpp, unittests/SQLiteReporterTest.cpp
1) Most probably Rust classes should be enabled via a preprocessor so this PR must also be extended with `#ifdefs`. Or Rust driver can take its driver and go as a separate target. **Maybe the whole test framework can go as a separate target?**
**decided to go with #ifdefs for now**
2) I don't like that `if/elseif` chain hanging in `main()` however the problem is that we are creating a pair of `finder/runner` based on the string input. Maybe this pair could be encapsulated behind umbrella class for a test framework like: `TestFramework` or smth like that?
**not decided but is not blocking this**
3) I have removed `debug_main` to remove redundancy and duplication. Our logger is now always set to the maximum `error` so the behavior should be preserved (didn't test yet).
=> Configure test framework from a config file.

lib/MutationOperators/NegateConditionMutationOperator.cpp
Otherwise, we may attempt to create an `ICmpInst` with `FCMP_*` predicate.
=> Construct CmpInst correctly

unittests/GoogleTest/GoogleTestFinderTest.cpp, unittests/MutationOperators/NegateConditionMutationOperatorTest.cpp, unittests/MutationPointTests.cpp
Only running mutations on distance == 1.
Before:
```
Tests:59
Mutants:109
Survived Mutants:17
Killed Mutants:92
Total time:4m 46s 305ms
Execution Time:1m 59s 95ms
Weakly Killed Mutants:16
Strongly Killed Mutants:76
Max distance:1
Min distance:1
Mean distance:1
Mutation Score:85%
```
After:
```
Tests:59
Mutants:109
Survived Mutants:12
Killed Mutants:97
Total time:2m 26s 436ms
Execution Time:1m 55s 345ms
Weakly Killed Mutants:14
Strongly Killed Mutants:83
Max distance:1
Min distance:1
Mean distance:1
Mutation Score:89%
```
=> Increase Mull's own mutation testing score.

lib/SQLiteReporter.cpp, unittests/SQLiteReporterTest.cpp
Before:
```
Tests:59
Mutants:110
Survived Mutants:14
Killed Mutants:96
Total time:3m 19s 118ms
Execution Time:2m 23s 439ms
Weakly Killed Mutants:18
Strongly Killed Mutants:78
Max distance:1
Min distance:1
Mean distance:1
Mutation Score:88%
```
After:
```
Tests:59
Mutants:110
Survived Mutants:12
Killed Mutants:98
Total time:2m 47s 20ms
Execution Time:2m 28s 560ms
Weakly Killed Mutants:13
Strongly Killed Mutants:85
Max distance:1
Min distance:1
Mean distance:1
Mutation Score:90%
```
=> Increase Mull's own mutation score: SQLiteReporterTest.

include/Result.h, tools/driver/driver.cpp, unittests/SQLiteReporterTest.cpp
> C++ has constructors. If it makes sense to initialize just one member then that can be expressed in the program by implementing an appropriate constructor. This is the sort of abstraction C++ promotes.
https://stackoverflow.com/questions/18731707/why-does-c11-not-support-designated-initializer-list-as-c99
=> Fix C99 designated initializer warnings.

Makefile.macos
```
mull (make)$ make -f Makefile.macos help
clean                Delete CMake build caches: Xcode and Ninja.
help                 Show this help message.
ninja.build          Build Ninja project with CMake.
ninja.clean          Delete Ninja CMake build cache.
ninja.test           Run Unit Tests (Builds Ninja cache first if it does not exist)
test                 Run unit tests (runs tests using Ninja)
xcode.build          Build Xcode project with CMake.
xcode.clean          Delete Xcode CMake build cache.
xcode.open           Open Mull.xcodeproj in Xcode
xcode.rebuild        Build Xcode project with CMake, kill Xcode, reopen the project in Xcode
xcode.reopen         Kill Xcode and open Mull.xcodeproj in Xcode.
```
=> Makefile: naming improvements.

include/MutationOperators/MutationOperatorsFactory.h, include/MutationPoint.h, include/TestFinder.h
```
../include/MutationsFinder.h:17:38: error: no member named 'unique_ptr' in namespace 'std'
```
=> CentOS: fix unique_ptr errors.

lib/MutationOperators/ScalarValueMutationOperator.cpp, unittests/MutationOperators/ScalarValueMutationOperatorTest.cpp, unittests/TestModuleFactory.cpp, unittests/TestModuleFactory.h, unittests/fixtures/openssl_bio_enc_test.o.ll
@stanislaw here is the example of failing scalar mutation operator.
Compilation of this mutation gives the following error:
```
LLVM ERROR: Cannot select: 0x621000091560: i32 = truncate 0x62100004c7a0
0x62100004c7a0: i8 = sub Constant:i8<0>, 0x621000048dd0
0x621000091480: i8 = Constant<0>
0x621000048dd0: i64,ch = load<LD4[%14], sext from i32> 0x6180000028b0, FrameIndex:i64<10>, undef:i64
0x621000091950: i64 = FrameIndex<10>
0x621000049700: i64 = undef
In function: do_bio_cipher
```
Happy debugging 😸
=> ScalarValueMutationOperator: do not affect the bit width of IntValue.

Docs/GettingStartedUbuntu.md
=> Docs/Ubuntu: LLVM 3.9 distribution has llvm-dev package now.

lib/SQLiteReporter.cpp
Goes after #318.
Metrics before/after this PR:
```
FMT:
Saving result: .................... 115ms
Saving result: .................... 10ms
LLVM:
Saving result: .................... 1188ms
Saving result: .................... 10ms
```
=> Optimize sqlite reporter

lib/ForkProcessSandbox.cpp
exit(3) called from ualarm's sighandler causes deadlock sometimes.
Switching to _exit(2) fixes the issue, but consequences of this change
are not clear yet.
Let's get that in and observe.
=> Use _exit(2) instead of exit(3).

include/Parallelization/Progress.h, lib/Parallelization/Progress.cpp
Simply prints dots when running from an IDE (Xcode/CLion).
=> Adapt progress_reporter to a non-terminal environment

unittests/MutatorsFactoryTests.cpp
Fixes compilation with clang 6.0.1 on my machine since std::functional is defined in functional header.
=> Add functional include

googletest/CMakeLists.txt, unittests/CMakeLists.txt
By default, when one runs `make install` cmake builds each and every
target, including `google-test` and `MullUnitTests`.
This patch excludes unneeded parts.
=> Exclude google-test and unit-tests from ALL

include/JunkDetection/CXX/CompilationDatabase.h, lab/junk_detection/compdb/CMakeLists.txt, lab/junk_detection/compdb/db_with_arguments.json, lab/junk_detection/compdb/db_with_commands.json, lab/junk_detection/compdb/db_with_fullpath_compiler.json, lab/junk_detection/compdb/db_with_output.json, lib/CMakeLists.txt, lib/JunkDetection/CXX/CompilationDatabase.cpp, lib/JunkDetection/CXX/CompilationDatabaseParser.h, unittests/CMakeLists.txt, unittests/JunkDetection/CompilationDatabaseTests.cpp
There are at least two reasons we do not use the CompilationDatabase from
Clang:
1. It expects a directory with a hardcoded filename
(compile_commands.json), which is a weird UX.
2. It silently eats the very first argument in the command/arguments
string, which is required on macOS in order to build the right header
search paths.
=> [Junk Detection] Introduce custom CompilationDatabase

include/JunkDetection/CXX/CompilationDatabase.h, lib/JunkDetection/CXX/CompilationDatabase.cpp, tools/driver-cxx/driver-cxx.cpp, unittests/JunkDetection/CompilationDatabaseTests.cpp
Junk Detection does not try to infer implicit include paths hardcoded into clang.
=> [JunkDetection] Rebrand compilation flags

cmake/version.cmake, include/Reporters/IDEReporter.h, lib/CMakeLists.txt, lib/Mutators/MutatorsFactory.cpp, lib/Mutators/NegateConditionMutator.cpp, lib/Reporters/IDEReporter.cpp, tools/driver-cxx/driver-cxx.cpp
Closes #439.
Example output:
```
Survived mutants (4/10):
/Users/alexdenisov/Projects/Mull/mull/Examples/HelloWorld/../../googletest/include/gtest/gtest.h:1397:10: warning: Remove Void Call: removed _ZN7testing8internal18CmpHelperEQFailureIiiEENS_15AssertionResultEPKcS4_RKT_RKT0_
return CmpHelperEQFailure(lhs_expression, rhs_expression, lhs, rhs);
^
/Users/alexdenisov/Projects/Mull/mull/Examples/HelloWorld/../../googletest/include/gtest/internal/gtest-port.h:1154:19: warning: Remove Void Call: removed _ZN7testing8internal10scoped_ptrINSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEE5resetEPS8_
~scoped_ptr() { reset(); }
^
/Users/alexdenisov/Projects/Mull/mull/Examples/HelloWorld/../../googletest/include/gtest/internal/gtest-port.h:1167:11: warning: Negate Condition: …
```
=> [mull-cxx] Introduce IDEReporter

CMakeLists.txt
=> Build only clang when building against monorepo

cmake/cpack.cmake, tools/driver-cxx/CMakeLists.txt
Fixes the following error:
```
CMake Error at cmake/cpack.cmake:47 (if):
if given arguments:
"STREQUAL" "macOS"
Unknown arguments specified
```
=> CPack: do not error on unknown OS; mull-cxx: support shared libLLVM

cmake/functions.cmake, tools/CMakeLists.txt, tools/driver-cxx/driver-cxx.cpp, tools/internal/CMakeLists.txt, tools/internal/mutator-validator/CMakeLists.txt, tools/internal/mutator-validator/mutator-validator.cpp
Closes #451.
Adds a new target to test mutators:
```
mutator-validator <mutator> <path to bitcode file>
```
=> Add target to validate mutations

README.md
Mull won't work will with the clang version that is bundled with xcode. It's better to have some warning on the readme.
This is related to the issue #521.
=> Update the the readme warning about using on macOS.

include/mull/Reporters/SourceManager.h, lib/CMakeLists.txt, lib/Reporters/IDEReporter.cpp, lib/Reporters/SourceManager.cpp
As requested in #517 [here](https://github.com/mull-project/mull/pull/517#discussion_r289600262), I am sending this changeset with a separate merge request.
No changes are involved, the code is simply moved to the separate header/source files.
=> Reporters: extract SourceManager to a separate class

CHANGELOG.md, cmake/version.cmake, include/mull/Version.h, lib/Version.cpp
Example:
```
> mull-cxx --version
Mull: LLVM-based mutation testing
https://github.com/mull-project/mull
Version: 0.3.0
Commit: e190672
Date: 08 Aug 2019
LLVM: 8.0.0
```
=> Include build date into the version info

CHANGELOG.md, include/mull/JunkDetection/CXX/Visitors/ReplaceAssignmentVisitor.h, include/mull/Mutators/Mutator.h, include/mull/Mutators/ReplaceAssignmentMutator.h, lib/CMakeLists.txt, lib/JunkDetection/CXX/CXXJunkDetector.cpp, lib/JunkDetection/CXX/Visitors/ReplaceAssignmentVisitor.cpp, tests/JunkDetection/CXXJunkDetectorTests.cpp, tests/fixtures/mutators/replace_assignment/CMakeLists.txt, tests/fixtures/mutators/replace_assignment/junk.cpp
It is important to understand that the Replace Assignment covers only
the following case:
```
int x = 0;  // <-- ignored
x = 31;     // <-- mutated
```
The line `int x = 0` is equivalent to the `int x(0)` which is in fact
a declaration, and not an assignment.
Fixes #482.
=> Junk Detection for ReplaceAssignment mutator

include/mull/Bitcode.h, lib/Bitcode.cpp, lib/Driver.cpp, lib/Parallelization/Tasks/SearchMutationPointsTask.cpp, tests/TestRunnersTests.cpp
This is how it works before the patch:
- find all the mutations
- put them into a bitcode file
- apply each mutation added to the bitcode file
The problem is that whenever the mutation is considered as junk and
removed from the execution pipeline it is still applied as if it would
run.
The patch moves adding of mutants to the bitcode only after all the junk
is filtered out.
---
Numbers for 38k mutants only 19 of which are not filtered out:
Before: ~20 minutes
```
Cloning functions for mutation (threads: 4): 4/4. Finished in 1167456ms.
Removing original functions (threads: 4): 4/4. Finished in 32479ms.
```
After: ~100ms
```
Cloning functions for mutation (threads: 4): 4/4. Finished in 79ms.
Removing original functions (threads: 4): 4/4. Finished in 36ms.
```
=> Apply only mutations that are not junk

include/mull/JunkDetection/CXX/ASTStorage.h, lib/JunkDetection/CXX/ASTStorage.cpp, lib/JunkDetection/CXX/CXXJunkDetector.cpp, lib/Mutators/CXX/RelationalMutators.cpp
Before this patch visitors traversed whole translation unit for each mutant,
within this patch, Mull traverses the only function that can potentially
contain the mutant.
---
On an example app I've got the following numbers (debug build):
Before:
- junk detection: 72s
- total: 108s
After:
- junk detection: 4s
- total: 40s
@stanislaw could you give it a try on your project and check is there is no regression?
I would also appreciate if you can share the numbers.
=> Speed up junk detection

include/mull/Toolchain/JITEngine.h, lib/Toolchain/JITEngine.cpp
Historically it was handled by the underlying JIT components, but I think since LLVM 8.0 we should handle this ourselves.
Since this part was removed from the dynamic loader we were simply getting NULLs instead of some functions, which led to a crash.
=> Report warming when a symbol cannot be resolved by JIT engine

tools/driver-cxx/driver-cxx.cpp
Without this building master fails with:
```
[ 98%] Building CXX object tools/driver-cxx/CMakeFiles/mull-cxx.dir/driver-cxx.cpp.o
mull/tools/driver-cxx/driver-cxx.cpp: In function ‘int main(int, char**)’:
mull/tools/driver-cxx/driver-cxx.cpp:188:3: error: member ‘tool::ReporterParameters::sourceInfoProvider’ is uninitialized reference
188 |   };
|   ^
mull/tools/driver-cxx/driver-cxx.cpp:188:3: error: designator order for field ‘tool::ReporterParameters::reporterName’ does not match declaration order in ‘tool::ReporterParameters’
```
=> Fix designator order in ReporterParameters initialization

docs/generated/CLIOptions.rst, lib/Mutators/MutatorsFactory.cpp, tests/MutatorsFactoryTests.cpp
AndOr is not reliable at the moment.
Steps to reproduce: run them against `fmt` example.
=> Move AndOr mutations to the experimental group

lib/Reporters/IDEReporter.cpp, tests-lit/tests/mutations/math/cxx_add_to_sub/02_basic/sample.cpp, tests-lit/tests/options/-ide-reporter-show-killed/01_one_killed/sample.cpp, tests-lit/tests/options/-ide-reporter-show-killed/02_one_survived/sample.cpp, tests-lit/tests/options/-ide-reporter-show-killed/03_one_surviving_one_killed/sample.cpp
It is important that we iterate over result.getMutationPoints() because we want
the output to be stable across multiple executions of Mull.
Optimizing this here was a bad idea: https://github.com/mull-project/mull/pull/640.
=> IDEReporter: revert to iterating over result's mutation points

docs/generated/CLIOptions.rst, include/mull/Diagnostics/Diagnostics.h, lib/Diagnostics/Diagnostics.cpp, tests-lit/tests/options/-debug/01-debug-option/sample.cpp, tests-lit/tests/options/-strict/01-strict-mode/sample.cpp, tools/driver-cxx/CLIOptions.cpp, tools/driver-cxx/CLIOptions.h, tools/driver-cxx/driver-cxx.cpp
Also error messages are always treated as fatal errors.
Closes #594
=> Strict mode: warning messages are treated as fatal errors 

docs/generated/CLIOptions.rst, include/mull/Config/Configuration.h, include/mull/Sandbox/ProcessSandbox.h, lib/Config/Configuration.cpp, lib/Parallelization/Tasks/MutantExecutionTask.cpp, lib/Parallelization/Tasks/OriginalTestExecutionTask.cpp, lib/Reporters/SQLiteReporter.cpp, lib/Sandbox/ProcessSandbox.cpp, tests/CustomTestFramework/CustomTestRunnerTests.cpp, tests/ProcessSandboxTest.cpp, tools/driver-cxx/CLIOptions.cpp, tools/driver-cxx/CLIOptions.h, tools/driver-cxx/driver-cxx.cpp
This information is not always required for further analysis, but it
greatly affects the size of an SQLite report: output strings may take
gigabytes
=> Add options to control stderr/stdout capturing

infrastructure/ubuntu-playbook.yaml, tests-lit/CMakeLists.txt, tests-lit/lit.cfg, tests-lit/tests/junk_detection/05_compilation_database_escaped_path/sample.cpp
And after the libc fix:
Closes #715
=> Enable LIT tests on CI for Linux

CMakeLists.txt, lib/CMakeLists.txt
This breaks FreeBSD builds (see https://github.com/mull-project/mull/issues/401),
but the FreeBSD builds are already broken...
=> Fix macOS build failure caused by pkg-config + sqlite3

lib/AST/ASTMutationStorage.cpp
They served their purpose very well for debugging small code, but on realistic
code it is very easy to hit them.
=> AST search: remove debug asserts

lib/AST/ASTVisitor.cpp, tests-lit/tests/white-ast-search/boundary/05_greater_than_to_2_mutations/compile_commands.json.template, tests-lit/tests/white-ast-search/boundary/05_greater_than_to_2_mutations/sample.cpp
This is a minor bug fix. The return prevents ASTVisitor from recording multiple
mutations if they originate from the same location in a source file.
=> AST Search: allow multiple binary mutations in one location

CMakeLists.txt
Avoids the need to specify it again if we run `cmake .` from the build directory.
=> cmake: Cache PATH_TO_LLVM variable

lib/Reporters/SourceManager.cpp
fgetc returns an int, however char was specified.
This fixes a case where the EOF is truncated to a char
which may not be detected depending on the sign of a char.
This issue is known to trigger on ppc64le.
=> reports: Fix a possible infinite loop in SourceManager

lib/CMakeLists.txt
This fixes a linking issue when building under ppc64le.
=> cmake: Link against native codegen and asmparser libs.

lib/Filters/FilePathFilter.cpp
Include will be applied first, then excludes.
If only include-path or only exclude-path is given then the behavior is unchanged from before.
This is useful if test code lives in the same tree as the code under test, so you can do `mull-cxx --include-path=mymodule --exclude-path=tests`
=> FilePathFilter: Allow combined include-path + exclude-path

lib/Driver.cpp, lib/Toolchain/JITEngine.cpp
This adds debug level messages for loading libraries and objects, and for resolving external references between objects and libraries.
Useful to better see what is going on inside mull-cxx during the prepare phase. This was written while debugging #743.
=> Add debug logging for object loading

include/mull/ExecutionResult.h, lib/Config/ConfigurationOptions.cpp, lib/Mutators/MutatorKind.cpp, tools/mull-cxx/CLIOptions.cpp
A couple of functions could previously return witout a return statment.
This updates the functions to always return the specified return type
by setting a defaulte case for most switch statements.
Signed-off-by: Evan Lojewski <github@meklort.com>
=> gcc: Fix build failures when building on GCC 10.

tools/mull-cxx/CLIOptions.cpp, tools/mull-cxx/CLIOptions.h, tools/mull-cxx/DynamicLibraries.cpp, tools/mull-cxx/DynamicLibraries.h, tools/mull-cxx/mull-cxx.cpp
As suggested in https://github.com/mull-project/mull/pull/745#issuecomment-694489990
This adds a new CLI option `-ld-preload` for providing preloaded dynamic libraries. The primary use case is to override libraries for test binaries which fail when recompiled, in particular those using C++ `thread_local` variables.
Forked off from #745 to make reviewing easier.
=> Add command line option -ld-preload

tests/CMakeLists.txt, vendor/CMakeLists.txt
=> CppUTest doesn't need to be added to the build system

CMakeLists.txt, tests/CMakeLists.txt
Use builtin support for discovering individual test cases in Google test with CTest.
This was mentioned in https://github.com/mull-project/mull/pull/759#issuecomment-702377209
This change allows us to use `ctest -j N` to run `N` tests in parallel instead of all sequentially. The drawback is that running the tests sequentially one-by-one when not using `-j N` takes more time than running the full unit test binary once with all test cases enabled because of the extra overhead from starting a new process for each test case.
Currently 183 test cases are registered. Running `ctest -j9` on my machine takes 1.9 seconds, while running the test binary without ctest takes 4.3 seconds, so not really a big difference right now. `ctest` without `-j` takes 7.4 seconds with this PR, 4.9 seconds without …
=> cmake: Use gtest_discover_tests for unit test enumeration

lib/Reporters/MutationTestingElementsReporter.cpp, tests/MutationTestingElementsReporterTest.cpp
Fixes #784
We somehow missed this requirement. Setting the version to 1.1.1 as it was the latest version when this feature was implemented.
=> Add MutationElements schema version

include/mull/Toolchain/Compiler.h, lib/Parallelization/Tasks/MutantPreparationTasks.cpp, lib/Toolchain/Compiler.cpp, lib/Toolchain/Toolchain.cpp, tests-lit/tests/mutations/math/cxx_add_to_sub/03_no_ret/sample.cpp, tests/CompilerTests.cpp
Without this fix Mull could generate the following code:
```
define void @foo_mutated() { ... }
define void @foo() {
call void @foo_mutated()
ret void <badref>
}
```
attempting to return the result of the stub call.
I could not find a case when it breaks the code in an observable way, but I believe we could've badly miscompiled some of the mutants 😬
=> Do not return value from a void stub

CMakeLists.txt, infrastructure/ubuntu-playbook.yaml, lib/CMakeLists.txt
Signal an error immediately in CMake instead of failing during
compilation if SQLite is not installed.
=> cmake: Search for SQLite3 during configuration phase

docs/Features.rst, docs/index.rst
It would be helpful for newcomers to describe Mull key features in a documentation.
=> Docs: add a page with a list of key features

include/mull/Driver.h, include/mull/Mutant.h, include/mull/MutationResult.h, include/mull/Parallelization/Tasks/DryRunMutantExecutionTask.h, include/mull/Parallelization/Tasks/MutantExecutionTask.h, include/mull/Result.h, lib/CMakeLists.txt, lib/Driver.cpp, lib/Mutant.cpp, lib/Parallelization/Tasks/DryRunMutantExecutionTask.cpp, lib/Parallelization/Tasks/MutantExecutionTask.cpp, lib/Reporters/IDEReporter.cpp, lib/Reporters/MutationTestingElementsReporter.cpp, lib/Reporters/SQLiteReporter.cpp, tests-lit/tests/deduplication/01/main.cpp, tests/MutationTestingElementsReporterTest.cpp, tests/SQLiteReporterTest.cpp
Closes #782
Now, the mutation point corresponds to the mutation on the bitcode level, while the mutant represents mutation on the source code level.
Ideally, we should move most of the properties to the mutant and leave the mutation point only with bitcode/mutator related info. But I think it makes sense to submit this move as a separate PR.
=> Deduplicate mutations by introducing a separate, higher-level entity

tests-lit/tests/invalid-input/05-elements-reporter-but-no-compdb/sample.cpp, tools/mull-cxx/CLIOptions.cpp
Strictly speaking, the compilation database is not required for the elements reporter to work.
Consider this simple example:
```
int sum(int a, int b) {
return a + b;
}
int main() {
return sum(15, -15);
}
```
The AST will be parsed just fine without any issues and the elements report will be generated correctly.
Having a strong requirement in this place forces me to provide a dummy `compilation-flags="-I."` which is a bit annoying.
Any objections @stanislaw? :)
=> Relax requirements for the Elements reporter

lib/Parallelization/Tasks/MutantPreparationTasks.cpp
Thanks for developing this awesome software!
I'm trying to use this for XCTest and Swift. Here is my WIP repository: https://github.com/kateinoigakukun/mull-xctest
Then Swift uses its own special calling convention and attributes, so call inst in trampoline func should also have those attributes.
=> Copy call inst attributions and calling convention

include/mull/Config/Configuration.h, include/mull/MutantRunner.h, include/mull/Parallelization/Tasks/MutantExecutionTask.h, lib/Config/Configuration.cpp, lib/Driver.cpp, lib/MutantRunner.cpp, lib/Parallelization/Tasks/MutantExecutionTask.cpp, lib/Toolchain/Linker.cpp, tests-lit/CMakeLists.txt, tests-lit/lit.cfg, tests-lit/tests/runner/01/main.c, tests-lit/tests/runner/01/test.py, tools/CLIOptions/CLIOptions.h, tools/mull-cxx/mull-cxx-cli.h, tools/mull-cxx/mull-cxx.cpp, tools/mull-runner/mull-runner-cli.h, tools/mull-runner/mull-runner.cpp
This PR concludes the implementation of #778.
What's left is documentation/tutorial, but that would come on the next iteration.
@ligurio, if you want to give it a try, then you can already try the following:
1. Generate mutated version of the program:
```
> mull-cxx -keep-executable \
-mutate-only \
-output=mutated-program \
-mutators=cxx_add_to_sub \
original-program-with-bitcode
```
2. Run the mutants against the separate test suite:
```
> mull-runner mutated-program  -test-program=python3  -- test-suite.py some "more arguments"
```
or
```
> mull-runner mutated-program  -test-program=test-suite.py  --  some "more arguments"
```
This is a very fresh implementation, so please consider it to be experimental :)
Any feedback is much appreciated!
=> Teach mull-runner about separate test programs

lib/MutationPoint.cpp
In my use case, mutants information is embedded in object files, and they are linked by linkers. But linkers can strip dead section (e.g. `-dead_strip` in ld64), so the special section should be marked with `llvm.used`.
=> Mark mutant record as llvm used to avoid dce

tests-lit/tests/cxx-frontend/mutations_in_macros/01_macro_add_to_sub/sample.cpp, tests-lit/tests/cxx-frontend/mutations_in_macros/02_macro_remove_void_function/sample.cpp, tests-lit/tests/cxx-frontend/mutations_in_macros/03_macro_add_to_sub_in_assert/sample.cpp, tools/mull-cxx-frontend/src/ASTMutationsSearchVisitor.cpp, tools/mull-cxx-frontend/src/ASTMutationsSearchVisitor.h
=> cxx-frontend: mutations in macros (two examples: add_to_sub and remove_void)

infrastructure/macos-playbook.yaml, infrastructure/ubuntu-playbook.yaml, tests-lit/tests/incremental-testing-using-git-diff/git-diff-filtering-of-llvm-ir-functions/_preconditions/03-warning-when-reading-git-diff-from-a-non-git-folder/test.itest, tests-lit/tests/options/-ide-reporter-show-killed/01_one_killed/sample.cpp, tests-lit/tests/options/-ide-reporter-show-killed/02_one_survived/sample.cpp
The new filecheck 0.0.18 contains a fix:
CHECK: regex lines: match full lines when strict mode is enabled #155
Before this fix, it was possible to pass a non-full line with a regex and it would work even though the strict mode flags were provided (--strict-whitespace and --match-full-lines).
=> tests-lit: fix two regex-based tests

tools/mull-cxx-frontend/src/ClangASTMutator.cpp
Building against LLVM/Clang source revealed that the getenv() function factory was not using correct types. With this change, consistent results are observed when comparing AST dump of getenv() created by AST and by hand.
=> cxx-frontend: fix the AST factory of getenv()

lib/Parallelization/Tasks/MutantExecutionTask.cpp
This important part was lost several months ago here https://github.com/mull-project/mull/commit/8346b8720648576e9355e9b0e8a153e150041d4f#diff-f353c4a77d760052da83fef010d3308cd3d51bcd91ff871cc984048d7f6626e4L37-R27
This is (hopefully) related to #890.
=> Set a reasonable lower bound value for the timeout

lib/Parallelization/Tasks/MutantExecutionTask.cpp
Now Mull shows the same output with enable and disabled debug mode on running
mutants. It contains only progress-bar with total and a number of run mutants:
[info] Warm up run (threads: 1)
[################################] 1/1. Finished in 26296ms
[info] Baseline run (threads: 1)
[################################] 1/1. Finished in 25931ms
[info] Running mutants (threads: 8)
[######################----------] 45608/65704
When an total time of mutation testing takes a lot of time it is useful to show
more information about current mutants, like file with mutant and status of
execution.
=> Print messages about current mutant in debug mode

docs/tutorials/SQLiteReport.rst
There was one reference to the `-test-framework` command line option in the documentation.
=> Remove last reference to test-framework

lib/Parallelization/Tasks/MutantExecutionTask.cpp
This clears the debugOutput after logging it, so it will no longer concat all the source locations.
=> Clear debugMessage in MutantExecution

lib/Toolchain/Runner.cpp
The incorrect order of drain and wait causes an incorrect recognition of failed original test and prolonged timeouts.
See https://github.com/DaanDeMeyer/reproc/blob/main/reproc%2B%2B/examples/drain.cpp#L50
=> Fixed order of drain and wait, as proposed in the example of reproc

include/mull/Reporters/SourceCodeReader.h, lib/Reporters/PatchesReporter.cpp, lib/Reporters/SourceCodeReader.cpp, tests-lit/tests/patch-reporter/multiline_patch/main.cpp
fix issue with multiline patch generation
=> Multiline patch fix

include/mull/Filters/FilePathFilter.h, lib/Filters/FilePathFilter.cpp, tests-lit/tests/xclude-regex/invalid_regex/sample.cpp, tests-lit/tests/xclude-regex/valid_regex/sample.cpp, tests/Mutations-E2E/CXX/Arithmetic/Mutation_Arithmetic_Add_Test.cpp, tests/Mutations-E2E/CXX/Arithmetic/Mutation_Arithmetic_UnaryMinusToNoop_Test.cpp, tests/Mutations-E2E/CXX/ConstAssignment/Mutation_ConstAssignment_AssignConst.cpp, tests/Mutations-E2E/CXX/ConstAssignment/Mutation_ConstAssignment_InitConst.cpp, tests/Mutations-E2E/CXX/RemoveNegationTest.cpp, tests/Mutations-E2E/Scalar/01_Mutation_Scalar_ReturnValue_Test.cpp, tests/Mutations-E2E/Scalar/02_Mutation_Scalar_BinaryOperand_Test.cpp, tools/mull-cxx/mull-cxx.cpp
As this is only possible by catching the exception the flag
-fno-exception has been removed
Fixes: https://github.com/mull-project/mull/issues/845
=> detect invalid regex

include/mull/FunctionUnderTest.h, lib/Driver.cpp, lib/FunctionUnderTest.cpp, lib/Parallelization/Tasks/SearchMutationPointsTask.cpp, tests-lit/tests/coverage/partial-covered-functions/main.c
This enables branch based coverage elimination.
Please check if this matches your expectation. I would suggest to have an additional switch to enable the line based coverage as it is quite a break in the behaviour compared to the current one.
Let me know what you think.
=> Enable more detailed coverage

lib/Parallelization/Tasks/MutantExecutionTask.cpp
The result status of the mutation run is just outputted as plain int, directly after the location.
With this PR, it is outputted as text.
=> Print execution status as String in debug output

docs/command-line/generated/mull-cxx-cli-options.rst, include/mull/Config/Configuration.h, lib/Config/Configuration.cpp, lib/Toolchain/Compiler.cpp, tools/CLIOptions/CLIOptions.h, tools/mull-cxx/mull-cxx-cli.h, tools/mull-cxx/mull-cxx.cpp
By lowering bitcode we do not respect the relocation model and various other target options.
Related: https://github.com/mull-project/mull/issues/903#issuecomment-972882621
=> Do not lower bitcode into machine code by default

include/mull/JunkDetection/CXX/ASTStorage.h, lib/Driver.cpp, lib/JunkDetection/CXX/ASTStorage.cpp, lib/JunkDetection/CXX/CXXJunkDetector.cpp, lib/JunkDetection/CXX/CompilationDatabase.cpp, tests-lit/tests/junk_detection/02_junk_detection_using_extra_flags/mull.no_flag.yml, tests-lit/tests/junk_detection/02_junk_detection_using_extra_flags/mull.with_flag.yml, tests-lit/tests/junk_detection/02_junk_detection_using_extra_flags/sample.cpp, tests-lit/tests/runner/mutants-from-dylib/mull.yml, tests-lit/tests/runner/mutants-from-dylib/test.c, tests/JunkDetection/CXXJunkDetectorTests.cpp, tests/JunkDetection/CompilationDatabaseTests.cpp, tests/fixtures/junk_detection/compdb/compile_commands.json.in, tools/mull-cxx-ir-frontend/CMakeLists.txt, tools/mull-cxx-ir-frontend/mull-cxx-ir-frontend.cpp
Having a test case for that is also tricky
=> Fix junk detection: getting the filenames right is tricky

include/mull/Config/Configuration.h, include/mull/Config/ConfigurationOptions.h, include/mull/Parallelization/Tasks/MutantPreparationTasks.h, lib/Config/ConfigurationParser.cpp, lib/Driver.cpp, lib/Parallelization/Tasks/MutantPreparationTasks.cpp, tests-lit/tests/debug/printIRAfter/main.c, tests-lit/tests/debug/printIRAfter/mull.yml, tests-lit/tests/debug/printIRBefore/main.c, tests-lit/tests/debug/printIRBefore/mull.yml, tests-lit/tests/debug/traceMutants/main.c, tests-lit/tests/debug/traceMutants/mull.yml, tests/MutationPointTests.cpp, tools/mull-cxx-ir-frontend/mull-cxx-ir-frontend.cpp
Very useful for debugging!
Adds the following options to `mull.yml`:
```
debug:
printIRBefore: true/false # print IR before transformations
printIRAfter: true/false # print IR after transformations
traceMutants: true/false # add various printfs to each mutated function
```
=> Add (optional) tracing to mutated programs

include/mull/Mutators/CXX/LogicalAndToOr.h, include/mull/Mutators/CXX/LogicalOrToAnd.h, lib/Mutators/CXX/LogicalAndToOr.cpp, lib/Mutators/CXX/LogicalOrToAnd.cpp, tests-lit/tests/mutations/logical/phi_nodes/main.c, tests-lit/tests/mutations/logical/phi_nodes/mull.yml
Fixes https://github.com/mull-project/mull/issues/994
=> Logical mutations: fix 'dangling' incoming phi-node value

cmake/functions.cmake, infrastructure/Vagrantfile, lib/CMakeLists.txt, tests/CMakeLists.txt, tests/MutationPointTests.cpp
I ran into some linking issues when building Mull on Arch due to libclangTooling.so being unavaiable. After doing some digging I came upon [this bug report](https://bugs.archlinux.org/task/66283) related to Arch's packaging of clang. Turns out its not a bug at all and that they are simply building clang without `BUILD_SHARED_LIBS=on`. When this flag is not passed, the symbols end up in libclang-cpp.so instead. 
This change makes the build system handle both options by first attempting to find libclangTooling.so and, if it's missing, fall back on libclang-cpp.so instead.
=> Fall back on clang-cpp.so if libclangTooling.so is unavailable

.gitignore, docs/command-line/generated/mull-runner-cli-options.rst, infrastructure/Vagrantfile, infrastructure/helpers/integration-tests.yaml, infrastructure/helpers/lit-tests.yaml, tests-lit/tests/filters/coverage/01/main.c, tests-lit/tests/filters/coverage/partial-covered-functions/main.c, tests-lit/tests/filters/junk-detection/00_error_compilation_flags_database_does_not_match_real_flags/sample.cpp, tests-lit/tests/filters/junk-detection/01_junk_detection/sample.cpp, tests-lit/tests/filters/junk-detection/02_junk_detection_using_extra_flags/sample.cpp, tests-lit/tests/filters/junk-detection/03_junk_detection_merging_comp_db_and_extra_flags/sample.cpp, tests-lit/tests/filters/junk-detection/04_junk_detection_using_bitcode_compilation_flags_via_record_command_line_flag/sample.cpp, tests-lit/tests/mutations/logical/and_or_combined/01/main.c, tests-lit/tests/mutations/logical/cxx_logical_and_to_or/01/main.c, tests-lit/tests/mutations/logical/cxx_logical_or_to_and/01/main.c, tests-lit/tests/mutations/logical/cxx_remove_negation/main.cpp, tests-lit/tests/mutations/logical/phi_nodes/main.c, tests-lit/tests/mutations/math/cxx_add_to_sub/03_no_ret/sample.cpp, tests-lit/tests/options/-ide-reporter-show-killed/02_one_survived/sample.cpp, tests-lit/tests/options/-ide-reporter-show-killed/03_one_surviving_one_killed/sample.cpp, tests-lit/tests/reporters/github-reporter/equality/main.cpp, tests-lit/tests/reporters/github-reporter/shift/main.cpp, tests-lit/tests/reporters/invalid-paths/main.c, tests-lit/tests/reporters/sqlite-reporter/equality/main.cpp, tests-lit/tests/runner/external-test-program/main.c, tests-lit/tests/tutorials/hello-world/step-1-version/sample.cpp, tests-lit/tests/tutorials/hello-world/step-3-one-survived-mutation/sample.cpp, tools/CLIOptions/CLIOptions.h, tools/mull-runner/mull-runner-cli.h, tools/mull-runner/mull-runner.cpp
The --help for strict mode states that "all warning messages are treated as fatal errors". While this is indeed true for anything that goes through Diagnostics::warning, there are a few messages presented as warnings that are not written via said function. The one (and at least so far only) concrete example I have come across are warnings written in printMutant in IDEReporter.cpp which emits messages similar to
```text
<file>:144:17: warning: Survived: Replaced > with >= [cxx_gt_to_ge]
if(currsize > size) {
^
```
Given the description for the --strict flag, it would seem as though the above should be considered a fatal error too. 
The warnings written in printMutant are currently written through fprintf. While it would be simple to change this this to use Diagnostics::warning instead, …
=> Disallow surviving mutants in strict mode

lib/JunkDetection/CXX/ASTStorage.cpp, lib/JunkDetection/CXX/CXXJunkDetector.cpp, lib/Mutators/CXX/NumberMutators.cpp, tests-lit/tests/ast-search/arithmetic/06_unary_minus_to_noop/sample.cpp, tests-lit/tests/ast-search/logical/cxx_remove_negation/01_unary_negated_to_unary/sample.cpp, tests-lit/tests/reporters/patch-reporter/cxx_assign_const/main.cpp, tests-lit/tests/reporters/patch-reporter/cxx_assign_const/mull.yml, tests-lit/tests/reporters/patch-reporter/cxx_minus_to_noop/main.cpp, tests-lit/tests/reporters/patch-reporter/cxx_minus_to_noop/mull.yml
Fixes https://github.com/mull-project/mull/issues/1025
=> Fix patch reporting for unary operators and CXXAssignConst

include/mull/Reporters/SourceManager.h, lib/Filters/CoverageFilter.cpp, lib/JunkDetection/CXX/ASTStorage.cpp, lib/Path.cpp, tests/Helpers/InMemoryCompiler.cpp, tools/mull-cxx-frontend/src/ASTNodeFactory.cpp, tools/mull-runner/MergeInstProfile.cpp
This PR adds support to build Mull with LLVM 17.
I have not yet updated any documentation or ci infrastructure. Please see if this can be incorporated into Mull, if any further modifications are required I can do so. This PR supports our [devcontainer](https://github.com/philips-software/amp-devcontainer) use-case.
=> Add support for LLVM 17

.github/workflows/ci-macos.yml, infrastructure/generator.py
LLVM 13 was removed from Homebrew on 31.12.2024
=> Remove LLVM 13 support on macOS

lib/Reporters/SQLiteReporter.cpp
Fixes a segfault hit when trying to use mull-reporter to combine multiple SQL reports.
https://github.com/mull-project/mull/issues/1086
=> Fix SQL reader error

lib/Reporters/SourceManager.cpp
When a file is not found in the compilation unit, mull errors out with "SourceManager: File or Directory Not Found".
This now adds the missing file name, to ease debugging.
=> Improve error messaging for file not found. 

lib/JunkDetection/CXX/ASTStorage.cpp, lib/JunkDetection/CXX/CompilationDatabase.cpp, lib/MutationPoint.cpp, tools/mull-reporter/mull-reporter.cpp, tools/mull-runner/DynamicLibraries.cpp, tools/mull-runner/MutantExtractor.cpp, tools/mull-runner/mull-runner.cpp
I ran into some trouble when wanting to use Mull with LLVM 19. Can't claim there is too much interesting in it the incompatibilities - mostly a few functions that have been either renamed or removed, and a few headers that now need to be included explicitly.
I won't claim that there changes include everything required for full LLVM 19 compatibility. I have, for example, made no effort to update the CI so this is definitely not on par with the work done when adding LLVM 18 support. Still, it ought to at least be a decent start. If you're interested in it, you're more than welcome to use it.
=> Support for building with LLVM 19
